# Generated by Django 2.2.12 on 2020-11-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pm',
            options={'verbose_name': '进度表', 'verbose_name_plural': '进度表'},
        ),
        migrations.AlterField(
            model_name='pm',
            name='ajtk_data',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='外包交付时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='ajtk_library_time',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='文库构建完成时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='ajtk_qc_time',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='样本质检完成时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='ajtk_receive_time',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='外包收样时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='ajtk_sample_type',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='外包收样时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='coun_analysis_time',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='遗传分析完成时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='counseling_yuyue',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='遗传咨询预约时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='data_analysis_time',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='数据分析完成时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='docoter_report',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='医生版报告出具时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='father_barcode',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='父亲样本条码核对'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='hospital',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='送检医院'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='kins_recevie_time',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='亲属样本到达时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='kinsfolk_sample',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='亲属送样情况'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='mark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='mather_barcode',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='母亲样本条码核对'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='other_barcode',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='其他样本条码核对'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='predict_data',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='预计数据下机'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='predict_report',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='预计出报告时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='predict_sanger_time',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='预计Sanger验证交付时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='receive_sanger_time',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Sanger验证交付时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='receive_time',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='样本接收时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='report_update_time',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='报告更新时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='representative',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='代表姓名'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='sanger_send_time',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Sanger验证送出时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='send_report_time',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='报告寄送时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='send_time',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='样本送检时间'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='user_report',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='患者版报告出具时间'),
        ),
    ]
