# Generated by Django 2.2.12 on 2020-11-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0002_auto_20201109_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm',
            name='clinical_info',
            field=models.TextField(blank=True, default=-9, null=True, verbose_name='有无临床信息'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='counseling_feedback',
            field=models.TextField(blank=True, default=-9, null=True, verbose_name='遗传咨询反馈结果'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='rep_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
    ]
