# Generated by Django 2.2.12 on 2020-11-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0003_auto_20201109_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm',
            name='ajtk_sample_type',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='外包样本类型'),
        ),
    ]
