# Generated by Django 2.2.12 on 2020-11-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0004_auto_20201109_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm',
            name='clinical_info',
            field=models.TextField(blank=True, default='', null=True, verbose_name='有无临床信息'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='counseling_feedback',
            field=models.TextField(blank=True, default='', null=True, verbose_name='遗传咨询反馈结果'),
        ),
    ]
