# Generated by Django 2.2.12 on 2021-01-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0008_auto_20201210_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm',
            name='product_type',
            field=models.CharField(max_length=50, verbose_name='产品类型'),
        ),
    ]
