# Generated by Django 2.2.12 on 2021-07-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc',
            name='cover20X',
            field=models.FloatField(default=-9, verbose_name='20X'),
        ),
    ]
