# Generated by Django 2.2.12 on 2022-08-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0002_qc_cover20x'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc',
            name='created_time',
            field=models.DateTimeField(auto_now=True, verbose_name='createdTime'),
        ),
    ]
