# Generated by Django 2.2.12 on 2022-08-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0003_qc_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qc',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='createdTime'),
        ),
    ]
