# Generated by Django 2.2.12 on 2022-08-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0004_auto_20220822_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qc',
            name='created_time',
            field=models.CharField(max_length=30, verbose_name='createdTime'),
        ),
    ]
