# Generated by Django 2.2.12 on 2020-04-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SangerSamples',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sampleName', models.CharField(max_length=50, verbose_name='sampleName')),
                ('chrom', models.CharField(max_length=5, verbose_name='chrom')),
                ('pos', models.PositiveIntegerField(verbose_name='pos')),
                ('ref', models.CharField(max_length=25, verbose_name='ref')),
                ('alt', models.CharField(max_length=25, verbose_name='alt')),
                ('genoType', models.CharField(max_length=25, verbose_name='genoType')),
                ('abiFileUrl', models.CharField(max_length=25, verbose_name='abiFileUrl')),
                ('abiPngUrl', models.CharField(max_length=25, verbose_name='abiPngUrl')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='createdTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updateTime')),
            ],
            options={
                'verbose_name': 'Sanger',
                'verbose_name_plural': 'Sanger',
            },
        ),
        migrations.CreateModel(
            name='SangerZipFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=50, verbose_name='fileName')),
                ('sampleNumbers', models.PositiveIntegerField(verbose_name='sampleNumbers')),
                ('status', models.IntegerField(choices=[(0, '分析成功'), (1, '分析失败')], default=0, verbose_name='status')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='createdTime')),
            ],
            options={
                'verbose_name': 'upload',
                'verbose_name_plural': 'upload',
            },
        ),
    ]
