# Generated by Django 2.2.12 on 2020-04-14 06:42

import Sanger.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sanger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sangersamples',
            name='abiFileUrl',
            field=models.CharField(max_length=255, verbose_name='abiFileUrl'),
        ),
        migrations.AlterField(
            model_name='sangersamples',
            name='abiPngUrl',
            field=models.ImageField(storage=Sanger.storage.FileStorage(), upload_to='uploadSanger/', verbose_name='abiPngUrl'),
        ),
        migrations.AlterField(
            model_name='sangersamples',
            name='pos',
            field=models.PositiveIntegerField(max_length=20, verbose_name='pos'),
        ),
        migrations.AlterField(
            model_name='sangerzipfiles',
            name='fileName',
            field=models.FileField(storage=Sanger.storage.FileStorage(), upload_to='uploadSanger/', verbose_name='fileName'),
        ),
        migrations.AlterField(
            model_name='sangerzipfiles',
            name='status',
            field=models.IntegerField(choices=[(0, '上传成功'), (1, '上传失败')], default=0, verbose_name='status'),
        ),
    ]
