# Generated by Django 2.2.12 on 2020-04-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sanger', '0002_auto_20200414_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sangersamples',
            name='pos',
            field=models.PositiveIntegerField(verbose_name='pos'),
        ),
    ]
