# Generated by Django 2.2.12 on 2020-04-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sanger', '0003_auto_20200414_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='sangerzipfiles',
            name='analysis',
            field=models.IntegerField(choices=[(0, '已分析'), (1, '未分析')], default=1, verbose_name='analysisStauts'),
        ),
    ]
