# Generated by Django 2.2.12 on 2020-04-20 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sanger', '0005_auto_20200420_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sangersamples',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='sangersamples',
            name='ref',
        ),
    ]
