# Generated by Django 2.2.12 on 2020-04-22 05:01

import Sanger.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sanger', '0006_auto_20200420_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='sangerzipfiles',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='updateTime'),
        ),
        migrations.AlterField(
            model_name='sangersamples',
            name='abiPngUrl',
            field=models.ImageField(max_length=255, storage=Sanger.storage.FileStorage(), upload_to='uploadSanger/', verbose_name='abiPngUrl'),
        ),
        migrations.AlterField(
            model_name='sangerzipfiles',
            name='fileName',
            field=models.FileField(max_length=255, storage=Sanger.storage.FileStorage(), upload_to='uploadSanger/', verbose_name='fileName'),
        ),
    ]
