# Generated by Django 2.2.12 on 2020-04-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sanger', '0010_auto_20200422_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sangerzipfiles',
            old_name='createdTime',
            new_name='created_time',
        ),
    ]
