# Generated by Django 2.2.12 on 2020-04-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sanger', '0011_auto_20200422_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sangerzipfiles',
            old_name='created_time',
            new_name='createdTime',
        ),
        migrations.RenameField(
            model_name='sangerzipfiles',
            old_name='update_time',
            new_name='updateTime',
        ),
    ]
