# Generated by Django 2.2.12 on 2020-09-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sanger', '0012_auto_20200422_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sangersamples',
            options={'verbose_name': 'Sanger结果', 'verbose_name_plural': 'Sanger结果'},
        ),
        migrations.AlterModelOptions(
            name='sangerzipfiles',
            options={'verbose_name': '数据上传', 'verbose_name_plural': '数据上传'},
        ),
    ]
