# Generated by Django 2.2.12 on 2021-02-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MT_QC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_id', models.IntegerField(verbose_name='sampleId')),
                ('sample_name', models.CharField(max_length=50, verbose_name='sampleName')),
                ('raw_bases', models.TextField(default=-9, verbose_name='rawBases')),
                ('raw_reads', models.TextField(default=-9, verbose_name='rawReads')),
                ('clean_reads', models.TextField(default=-9, verbose_name='cleanReads')),
                ('map_reads', models.TextField(default=-9, verbose_name='mappingReads')),
                ('map_rate', models.FloatField(default=-9, verbose_name='mappingRate')),
                ('dedup_reads', models.TextField(default=-9, verbose_name='dedupReads')),
                ('dedup_rate', models.FloatField(default=-9, verbose_name='dedupRate')),
                ('target_reads', models.TextField(default=-9, verbose_name='teargetReads')),
                ('capture_rate', models.FloatField(default=-9, verbose_name='captureRate')),
                ('mean_depth_raw', models.FloatField(default=-9, verbose_name='meanDepthRaw')),
                ('mean_depth', models.FloatField(default=-9, verbose_name='meanDepth')),
            ],
            options={
                'verbose_name': 'MT_QC',
                'verbose_name_plural': 'MT_QC',
            },
        ),
    ]
