# Generated by Django 2.2.12 on 2021-11-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MT_QC', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mt_qc',
            old_name='mean_depth',
            new_name='chrM_mean_depth',
        ),
        migrations.RenameField(
            model_name='mt_qc',
            old_name='mean_depth_raw',
            new_name='chrM_mean_depth_raw',
        ),
    ]
