# Generated by Django 2.2.12 on 2020-09-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DD_QC', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QC',
            new_name='DD_QC',
        ),
    ]
