# Generated by Django 2.2.12 on 2020-09-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0004_auto_20200914_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processanalysis',
            name='cnv',
            field=models.CharField(max_length=50, null=True, verbose_name='CNV分析结果'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='data_complete_analysis',
            field=models.CharField(max_length=25, null=True, verbose_name='原始数据分析完成时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='first_check',
            field=models.CharField(max_length=50, null=True, verbose_name='一审人+完成时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='mark',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='predict_data',
            field=models.CharField(max_length=25, null=True, verbose_name='预计下机时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='predict_report',
            field=models.CharField(max_length=25, null=True, verbose_name='预计出报告时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='receive_time',
            field=models.CharField(max_length=25, null=True, verbose_name='收样日期'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='report_check',
            field=models.CharField(max_length=50, null=True, verbose_name='报告审核人+完成时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='report_day',
            field=models.CharField(max_length=10, null=True, verbose_name='报告周期/自然日'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='report_time',
            field=models.CharField(max_length=20, null=True, verbose_name='报告完成时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='report_writer',
            field=models.CharField(max_length=50, null=True, verbose_name='报告撰写人+完成时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='sanger',
            field=models.CharField(max_length=25, null=True, verbose_name='Sanger验证位点'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='sanger_check',
            field=models.CharField(max_length=25, null=True, verbose_name='Sanger验证位点是否一致'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='sanger_complete_time',
            field=models.CharField(max_length=25, null=True, verbose_name='Sanger测序完成时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='sanger_send_time',
            field=models.CharField(max_length=25, null=True, verbose_name='Sanger测序送测时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='second',
            field=models.CharField(max_length=50, null=True, verbose_name='二审人+完成时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='send_time',
            field=models.CharField(max_length=25, null=True, verbose_name='送检日期'),
        ),
    ]
