# Generated by Django 2.2.12 on 2020-09-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0005_auto_20200914_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sample_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='患者编号')),
                ('Sample_proper', models.CharField(blank=True, max_length=50, null=True, verbose_name='样本性质')),
                ('User_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='患者姓名')),
                ('Sex', models.CharField(blank=True, max_length=5, null=True, verbose_name='性别')),
                ('Birth', models.CharField(blank=True, max_length=20, null=True, verbose_name='出生日期')),
                ('Age', models.CharField(blank=True, max_length=20, null=True, verbose_name='年龄')),
                ('Clinical', models.TextField(blank=True, null=True, verbose_name='临床表现')),
                ('Report_result', models.TextField(blank=True, null=True, verbose_name='报告结果')),
                ('Exon_table1', models.TextField(blank=True, null=True, verbose_name='外显子组表1')),
                ('Exon_table2', models.TextField(blank=True, null=True, verbose_name='外显子组表2')),
                ('Exon_table3', models.TextField(blank=True, null=True, verbose_name='外显子组表3')),
                ('ChrM', models.TextField(blank=True, null=True, verbose_name='线粒体基因组')),
                ('CNV', models.TextField(blank=True, null=True, verbose_name='CNV')),
                ('Acmg', models.TextField(blank=True, null=True, verbose_name='ACMG')),
                ('Report_diagnose', models.TextField(blank=True, null=True, verbose_name='初步诊断')),
                ('Doctor_diagnose', models.TextField(blank=True, null=True, verbose_name='遗传咨询后诊断')),
                ('Organize_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='医院')),
                ('Region', models.CharField(blank=True, max_length=50, null=True, verbose_name='大区')),
                ('Product', models.CharField(blank=True, max_length=50, null=True, verbose_name='产品')),
                ('Detect_project', models.CharField(blank=True, max_length=50, null=True, verbose_name='检测项目')),
                ('Send_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='送检日期')),
                ('Received_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='收样日期')),
                ('Cal_report_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='预计报告日期')),
                ('Real_report_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='报告日期')),
                ('PaternalInfoId', models.CharField(blank=True, max_length=50, null=True, verbose_name='父亲样本编号')),
                ('PaternalResult', models.TextField(blank=True, null=True, verbose_name='父亲验证结果')),
                ('MaternalInfoId', models.CharField(blank=True, max_length=50, null=True, verbose_name='母亲样本编号')),
                ('MaternalResult', models.TextField(blank=True, null=True, verbose_name='母亲验证结果')),
                ('CompatriotInfoId', models.CharField(blank=True, max_length=50, null=True, verbose_name='同胞样本编号')),
                ('CompatriotResult', models.TextField(blank=True, null=True, verbose_name='同胞验证结果')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='updateTime')),
            ],
            options={
                'verbose_name': 'SampleInfo',
                'verbose_name_plural': 'SampleInfo',
            },
        ),
    ]
