# Generated by Django 2.2.12 on 2020-09-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0008_sampleinfo_sample_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneDisease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gene', models.CharField(max_length=50, verbose_name='基因')),
                ('disease', models.CharField(max_length=255, verbose_name='疾病')),
                ('genetic_model', models.CharField(max_length=50, verbose_name='遗传模式')),
                ('morbidity', models.CharField(max_length=255, verbose_name='外显率')),
                ('clinical_feature', models.TextField(verbose_name='临床表现')),
                ('clinical_intervention', models.TextField(verbose_name='临床干预')),
                ('case_manage', models.TextField(verbose_name='患者管理')),
                ('clinical_monitoring', models.TextField(verbose_name='临床监测')),
                ('avoid', models.TextField(verbose_name='需要避免的情况')),
                ('risk_assessment', models.TextField(verbose_name='家系成员患病风险评估')),
                ('reason', models.TextField(verbose_name='可能存在临床检测阴性的原因')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='createdTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updateTime')),
            ],
            options={
                'verbose_name': 'GeneDisease',
                'verbose_name_plural': 'GeneDisease',
            },
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='CompatriotInfoId',
            field=models.TextField(blank=True, null=True, verbose_name='同胞样本编号'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='Update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updateTime'),
        ),
    ]
