# Generated by Django 2.2.12 on 2020-09-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0009_auto_20200916_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='genedisease',
            name='morbidity_age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='发病年龄'),
        ),
        migrations.AddField(
            model_name='genedisease',
            name='omim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MIM'),
        ),
        migrations.AddField(
            model_name='genedisease',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name='其他'),
        ),
        migrations.AddField(
            model_name='genedisease',
            name='penetrance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='外显率'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='avoid',
            field=models.TextField(blank=True, null=True, verbose_name='需要避免的情况'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='case_manage',
            field=models.TextField(blank=True, null=True, verbose_name='患者管理'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='clinical_feature',
            field=models.TextField(blank=True, null=True, verbose_name='临床表现'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='clinical_intervention',
            field=models.TextField(blank=True, null=True, verbose_name='临床干预'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='clinical_monitoring',
            field=models.TextField(blank=True, null=True, verbose_name='临床监测'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='createdTime'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='disease',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='疾病'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='genetic_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='遗传模式'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='morbidity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='发病率'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='可能存在临床检测阴性的原因'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='risk_assessment',
            field=models.TextField(blank=True, null=True, verbose_name='家系成员患病风险评估'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='updateTime'),
        ),
    ]
