# Generated by Django 2.2.12 on 2020-09-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0010_auto_20200917_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genedisease',
            name='gene',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='基因'),
        ),
    ]
