# Generated by Django 2.2.12 on 2020-09-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0011_auto_20200918_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genedisease',
            name='disease',
            field=models.TextField(blank=True, null=True, verbose_name='疾病'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='gene',
            field=models.TextField(blank=True, null=True, verbose_name='基因'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='genetic_model',
            field=models.TextField(blank=True, null=True, verbose_name='遗传模式'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='morbidity',
            field=models.TextField(blank=True, null=True, verbose_name='发病率'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='morbidity_age',
            field=models.TextField(blank=True, null=True, verbose_name='发病年龄'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='omim',
            field=models.TextField(blank=True, null=True, verbose_name='MIM'),
        ),
        migrations.AlterField(
            model_name='genedisease',
            name='penetrance',
            field=models.TextField(blank=True, null=True, verbose_name='外显率'),
        ),
    ]
