# Generated by Django 2.2.12 on 2020-09-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0013_auto_20200921_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processanalysis',
            options={'ordering': ('-id',), 'verbose_name': '遗传分析流程进度', 'verbose_name_plural': '遗传分析流程进度'},
        ),
    ]
