# Generated by Django 2.2.12 on 2020-11-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0014_auto_20200925_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processanalysis',
            options={'ordering': ('-sample_id',), 'verbose_name': '遗传分析流程进度', 'verbose_name_plural': '遗传分析流程进度'},
        ),
        migrations.AlterModelOptions(
            name='sampleinfo',
            options={'ordering': ('-sample_id',), 'verbose_name': 'SampleInfo', 'verbose_name_plural': 'SampleInfo'},
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='other_sample',
            field=models.CharField(max_length=255, null=True, verbose_name='亲属样本条码'),
        ),
    ]
