# Generated by Django 2.2.12 on 2020-11-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0015_auto_20201102_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='processanalysis',
            name='age',
            field=models.CharField(max_length=50, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='sex',
            field=models.CharField(max_length=25, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='cnv',
            field=models.TextField(null=True, verbose_name='CNV分析结果'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='doctor_report',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='医生版上传日期'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='first_check',
            field=models.CharField(max_length=100, null=True, verbose_name='一审人+完成时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='report_check',
            field=models.CharField(max_length=100, null=True, verbose_name='报告审核人+完成时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='report_time',
            field=models.CharField(max_length=50, null=True, verbose_name='报告完成时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='report_writer',
            field=models.CharField(max_length=100, null=True, verbose_name='报告撰写人+完成时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='sanger',
            field=models.CharField(max_length=100, null=True, verbose_name='Sanger验证位点'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='sanger_check',
            field=models.CharField(max_length=100, null=True, verbose_name='Sanger验证位点是否一致'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='sanger_complete_time',
            field=models.CharField(max_length=100, null=True, verbose_name='Sanger测序完成时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='sanger_send_time',
            field=models.CharField(max_length=100, null=True, verbose_name='Sanger测序送测时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='second',
            field=models.CharField(max_length=100, null=True, verbose_name='二审人+完成时间'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='user_report',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='患者版上传日期'),
        ),
    ]
