# Generated by Django 2.2.12 on 2020-11-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0016_auto_20201118_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processanalysis',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='sex',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='性别'),
        ),
    ]
