# Generated by Django 2.2.12 on 2020-11-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0017_auto_20201118_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processanalysis',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='出生日期'),
        ),
    ]
