# Generated by Django 2.2.12 on 2021-01-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0018_auto_20201118_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='zzxProcessAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_id', models.IntegerField(verbose_name='序号')),
                ('mark', models.TextField(null=True, verbose_name='备注')),
                ('sex', models.CharField(blank=True, max_length=25, null=True, verbose_name='性别')),
                ('age', models.CharField(blank=True, max_length=50, null=True, verbose_name='出生日期')),
                ('sample_name', models.CharField(max_length=50, verbose_name='样本编号')),
                ('user_name', models.CharField(max_length=10, verbose_name='患者姓名')),
                ('other_sample', models.CharField(max_length=255, null=True, verbose_name='亲属样本条码')),
                ('hospital', models.CharField(max_length=50, verbose_name='送检医院')),
                ('area', models.CharField(max_length=25, verbose_name='大区')),
                ('representative', models.CharField(max_length=10, verbose_name='代表')),
                ('product_type', models.CharField(max_length=10, verbose_name='产品类型')),
                ('send_time', models.CharField(max_length=25, null=True, verbose_name='送检日期')),
                ('receive_time', models.CharField(max_length=25, null=True, verbose_name='收样日期')),
                ('predict_data', models.CharField(max_length=25, null=True, verbose_name='预计下机时间')),
                ('predict_report', models.CharField(max_length=25, null=True, verbose_name='预计出报告时间')),
                ('data_complete_analysis', models.CharField(max_length=25, null=True, verbose_name='原始数据分析完成时间')),
                ('first_check', models.CharField(max_length=100, null=True, verbose_name='一审人+完成时间')),
                ('sanger', models.CharField(max_length=100, null=True, verbose_name='Sanger验证位点')),
                ('second', models.CharField(max_length=100, null=True, verbose_name='二审人+完成时间')),
                ('sanger_check', models.CharField(max_length=100, null=True, verbose_name='Sanger验证位点是否一致')),
                ('sanger_send_time', models.CharField(max_length=100, null=True, verbose_name='Sanger测序送测时间')),
                ('sanger_complete_time', models.CharField(max_length=100, null=True, verbose_name='Sanger测序完成时间')),
                ('cnv', models.TextField(null=True, verbose_name='CNV分析结果')),
                ('report_writer', models.CharField(max_length=100, null=True, verbose_name='报告撰写人+完成时间')),
                ('report_check', models.CharField(max_length=100, null=True, verbose_name='报告审核人+完成时间')),
                ('report_time', models.CharField(max_length=50, null=True, verbose_name='报告完成时间')),
                ('doctor_report', models.CharField(blank=True, max_length=25, null=True, verbose_name='医生版上传日期')),
                ('user_report', models.CharField(blank=True, max_length=25, null=True, verbose_name='患者版上传日期')),
                ('report_day', models.CharField(max_length=10, null=True, verbose_name='报告周期/自然日')),
            ],
            options={
                'verbose_name': '臻智选流程进度',
                'verbose_name_plural': '臻智选流程进度',
                'ordering': ('-sample_id',),
            },
        ),
        migrations.AlterModelOptions(
            name='processanalysis',
            options={'ordering': ('-sample_id',), 'verbose_name': '贝安臻流程进度', 'verbose_name_plural': '贝安臻流程进度'},
        ),
    ]
