# Generated by Django 2.2.12 on 2021-02-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0020_remove_zzxprocessanalysis_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processanalysis',
            name='product_type',
            field=models.CharField(max_length=25, verbose_name='产品类型'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='report_day',
            field=models.CharField(max_length=25, null=True, verbose_name='报告周期/自然日'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='representative',
            field=models.CharField(max_length=25, verbose_name='代表'),
        ),
    ]
