# Generated by Django 2.2.12 on 2021-10-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0023_auto_20210915_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processanalysis',
            name='product_type',
            field=models.CharField(max_length=50, verbose_name='产品类型'),
        ),
        migrations.AlterField(
            model_name='zkanalysis',
            name='product_type',
            field=models.CharField(max_length=50, verbose_name='产品类型'),
        ),
    ]
