# Generated by Django 2.2.12 on 2022-02-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0024_auto_20211012_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processanalysis',
            name='user_name',
            field=models.CharField(max_length=30, verbose_name='患者姓名'),
        ),
    ]
