# Generated by Django 2.2.12 on 2022-08-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0026_zzxprocessanalysis_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='processanalysis',
            name='re_ana_date',
            field=models.CharField(max_length=25, null=True, verbose_name='重分析日期'),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='re_ana_result',
            field=models.CharField(max_length=100, null=True, verbose_name='重分析结果'),
        ),
    ]
