# Generated by Django 2.2.12 on 2023-11-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genetic_Counseling', '0027_auto_20220808_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genedisease',
            name='avoid',
        ),
        migrations.RemoveField(
            model_name='genedisease',
            name='case_manage',
        ),
        migrations.RemoveField(
            model_name='genedisease',
            name='clinical_feature',
        ),
        migrations.RemoveField(
            model_name='genedisease',
            name='clinical_intervention',
        ),
        migrations.RemoveField(
            model_name='genedisease',
            name='clinical_monitoring',
        ),
        migrations.RemoveField(
            model_name='genedisease',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='genedisease',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='genedisease',
            name='genetic_model',
        ),
        migrations.RemoveField(
            model_name='genedisease',
            name='morbidity',
        ),
        migrations.RemoveField(
            model_name='genedisease',
            name='morbidity_age',
        ),
        migrations.RemoveField(
            model_name='genedisease',
            name='omim',
        ),
        migrations.RemoveField(
            model_name='genedisease',
            name='other',
        ),
        migrations.RemoveField(
            model_name='genedisease',
            name='penetrance',
        ),
        migrations.RemoveField(
            model_name='genedisease',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='genedisease',
            name='risk_assessment',
        ),
        migrations.AddField(
            model_name='genedisease',
            name='CHPO_All_Terms',
            field=models.TextField(blank=True, null=True, verbose_name='CHPO_All_Terms'),
        ),
        migrations.AddField(
            model_name='genedisease',
            name='Disease_Description_CH',
            field=models.TextField(blank=True, null=True, verbose_name='Disease_Description_CH'),
        ),
        migrations.AddField(
            model_name='genedisease',
            name='Disease_OMIM_ID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Disease_OMIM_ID'),
        ),
        migrations.AddField(
            model_name='genedisease',
            name='Gene',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gene'),
        ),
        migrations.AddField(
            model_name='genedisease',
            name='Gene_Description_CH',
            field=models.TextField(blank=True, null=True, verbose_name='Gene_Description_CH'),
        ),
        migrations.AddField(
            model_name='genedisease',
            name='Gene_OMIM_ID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gene_OMIM_ID'),
        ),
        migrations.AddField(
            model_name='genedisease',
            name='HPO_All_Terms',
            field=models.TextField(blank=True, null=True, verbose_name='HPO_All_Terms'),
        ),
        migrations.AddField(
            model_name='genedisease',
            name='OMIM_Clinical_Synopses',
            field=models.TextField(blank=True, null=True, verbose_name='OMIM_Clinical_Synopses'),
        ),
        migrations.AddField(
            model_name='genedisease',
            name='OMIM_Clinical_Synopses_CH',
            field=models.TextField(blank=True, null=True, verbose_name='OMIM_Clinical_Synopses_CH'),
        ),
        migrations.AddField(
            model_name='genedisease',
            name='OMIM_Disease',
            field=models.TextField(blank=True, null=True, verbose_name='OMIM_Disease'),
        ),
        migrations.AddField(
            model_name='genedisease',
            name='OMIM_Disease_CH',
            field=models.TextField(blank=True, null=True, verbose_name='OMIM_Disease_CH'),
        ),
        migrations.AddField(
            model_name='genedisease',
            name='OMIM_Inhert',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OMIM_Inhert'),
        ),
    ]
